In [239]:
import pandas as pd

# Replace the file path with your actual file path
file_path = r'C:\Users\relia\Documents\GitHub\Bridges\Data\sr_co_mostydc_reportpk_2024-01-01.csv'

# Import CSV file as DataFrame with specified encoding
df_2024 = pd.read_csv(file_path, encoding='windows-1250')

# Now df_2024 contains your data from the CSV file

C:\Users\relia\AppData\Local\Temp\ipykernel_2744\2079872364.py:7: DtypeWarning: Columns (9,24,54) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv(file_path, encoding='windows-1250')

In [221]:
# Define a function to remove the suffix from the ID
def remove_suffix(id):
    return id.split('.')[0] if isinstance(id, str) else id


# Apply the function to the "ID DC" column
df_2024['ID DC'] = df_2024['ID DC'].apply(remove_suffix)

In [222]:
df_2024.columns

Index(['Trieda PK', 'Číslo PK', 'Most /DC', 'Názov mosta', 'ID mosta', 'ID DC',
       'správcovské číslo', 'Stavebno-technický stav', 'Longitude', 'Latitude',
       'Vyska', 'Druh konštrukcie', 'Material', 'Normána zaťažiteľnost / t',
       'Výhradná zaťažiteľnosť / t', 'Výnimočná zaťažiteľnosť / t',
       'Spôsob stanovenia', 'Predmet premostenia', 'Rok postavenia',
       'Zaťažovacia trieda STN', 'Počet otvorov', 'Dĺžka premostenia / m',
       'Dĺžka nosnej konštrukcie / m', 'Volná šírka mosta/ m',
       'Šírka medzi obrubami/ m', 'Pocha mosnej konštrukcie / m2',
       'Plocha mosta / m2', 'Vlastník mostu', 'Správca mostu', 'Okres',
       'Smer úseku', 'Typ úseku', 'Počiatočný uzol', 'Koncový uzol', 'úsek ID',
       'úsekové staničenie začiatku DC / m',
       'Kilometrovníkové staničenie začiatku DC / km',
       'Kumulatívne staničenie začiatku DC / km', 'Poradie', 'Vlastník úseku',
       'Správca úseku', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43',
       'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47',
       'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51',
       'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54'],
      dtype='object')

In [223]:
# Define a function to check if a given ID is valid based on your criteria
def is_valid_id(id_value):
    return isinstance(id_value, str) and id_value.startswith('M') and id_value[1:].isdigit()

# Function to find a valid ID from four columns and replace if needed


def replace_invalid_id(row):
    # Check if 'ID mosta' is valid
    if not is_valid_id(row['ID mosta']):
        # Attempt to replace from 'ID DC' if valid
        if is_valid_id(row['ID DC']):
            return row['ID DC']
        # Next, try 'správcovské číslo' if valid
        elif is_valid_id(row['správcovské číslo']):
            return row['správcovské číslo']
        # Then check 'Stavebno-technický stav' if valid
        elif is_valid_id(row['Stavebno-technický stav']):
            return row['Stavebno-technický stav']
        else:
            # Return original if no valid replacement found
            return row['ID mosta']
    else:
        return row['ID mosta']  # Return original if it is already valid


# Filter for entries where 'Most /DC' equals "Most"
df_most = df_2024[df_2024['Most /DC'] == "Most"].copy()

# Apply the function to replace invalid 'ID mosta'
df_most['ID mosta'] = df_most.apply(replace_invalid_id, axis=1)

# Update the main DataFrame with cleaned 'ID mosta' values
df_2024.update(df_most['ID mosta'])

In [224]:
# Set the values in the "ID DC" column to NaN for rows where df_2024['Most /DC'] == "Most"
df_2024.loc[df_2024['Most /DC'] == "Most", 'ID DC'] = None

In [225]:
df_2024

,Trieda PK,Číslo PK,Most /DC,Názov mosta,ID mosta,ID DC,správcovské číslo,Stavebno-technický stav,Longitude,Latitude,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54
0,cesta I. triedy,10,Most,18_235 Most cez bezmenný potok Pod Bumbálkou,M262,None,235,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,cesta I. triedy,10,Dilatačný celok,NaN,NaN,M262,NaN,Uspokojivý,18.4090472760,49.3957569940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,cesta I. triedy,10,Most,18_236 Most cez bezmenný potok,M1915,None,NaN,236,NaN,NaN,...,SSC - IVSC ZA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,cesta I. triedy,10,Dilatačný celok,NaN,NaN,M1915,NaN,Zlý,18.4254208190,49.3797328400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,cesta I. triedy,10,Most,18_237 Most cez potok Trojačka v obci Makov,M4803,None,237,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18697,účelová cesta (UC),UK,Dilatačný celok,NaN,NaN,M10136,NaN,Uspokojivý,18.0641300000,48.33948,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18698,účelová cesta (UC),UK,Most,66-108A_Most na ceste I/66 ponad poľnú cestu a...,M10217,None,108A,NaN,NaN,NaN,...,NaN,NaN,NaN,STAT,SSC - IVSC BB,NaN,NaN,NaN,NaN,NaN
18699,účelová cesta (UC),UK,Dilatačný celok,NaN,NaN,M10217,NaN,Dobrý,19.6548000000,48.8006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18700,účelová cesta (UC),UK,Most,66-108B_Most nad účelovou komunikáciou,M10218,None,108B,NaN,NaN,NaN,...,NaN,NaN,STAT,SSC - IVSC BB,NaN,NaN,NaN,NaN,NaN,NaN
18701,účelová cesta (UC),UK,Dilatačný celok,NaN,NaN,M10218,NaN,Dobrý,19.6596000000,48.8002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
# Split the DataFrame into two separate DataFrames based on the values in the "Most /DC" column
df_bridges = df_2024[df_2024['Most /DC'] == 'Most'].copy()[["ID mosta"]]
df_DC = df_2024[df_2024['Most /DC'] == 'Dilatačný celok'].copy()

# Remove duplicates from the "ID mosta" column
df_bridges = df_bridges.drop_duplicates(subset=["ID mosta"])

In [227]:
df_bridges["ID mosta"].value_counts(), df_DC["ID DC"].value_counts()

(ID mosta
 M262      1
 M405      1
 M4373     1
 M6384     1
 M603      1
          ..
 M7748     1
 M3473     1
 M7539     1
 M3605     1
 M10218    1
 Name: count, Length: 8468, dtype: int64,
 ID DC
 M1573     12
 M7405      7
 M9474      7
 M9588      6
 M6893      6
           ..
 M3931      1
 M183       1
 M409       1
 M2209      1
 M10218     1
 Name: count, Length: 8468, dtype: int64)

In [228]:
# Define the mapping of conditions to their respective values
condition_mapping = {
    'Zlý': 5,
    'Veľmi zlý': 6,
    'Uspokojivý': 4,
    'Bezchybný': 1,
    'Dobrý': 3,
    'Havarijný': 7,
    'Nezistený': 0,
    'Veľmi dobrý': 2
}

# Map the values from 'Stavebno-technický stav' column to 'n_2024' based on the condition_mapping
df_DC['n_2024'] = df_DC['Stavebno-technický stav'].map(condition_mapping)

In [229]:
# Iterate over each row in df_bridges
for index, row in df_bridges.iterrows():
    id_mosta = row["ID mosta"]
    # Find matching rows in df_DC
    matching_rows = df_DC[df_DC["ID DC"] == id_mosta]

    # Calculate the mean of "n_2024" values for the matching rows
    mean_n_2024 = matching_rows["n_2024"].mean()

    # Assign the mean value to the corresponding row in df_bridges
    df_bridges.at[index, "n_2024"] = mean_n_2024

In [230]:
bridges_path = r"C:\Users\relia\Documents\GitHub\Bridges\Data\df_bridges_data.csv"
df_bridges_all = pd.read_csv(bridges_path, encoding='utf-8', delimiter=',')
df_bridges_all.columns

Index(['ID_mosta', 'Trieda_PK', 'Číslo_PK', 'Most_DC', 'Názov_mosta', 'ID_DC',
       'správcovské_číslo', 'Zemepisná_šírka', 'Zemepisná_dĺžka', 'Výška',
       'Druh_konštrukcie', 'Material', 'Normálna_zaťažiteľnosť',
       'Výhradná_zaťažiteľnosť_t', 'Výnimočná_zaťažiteľnosť_t',
       'Spôsob_stanovenia', 'Predmet_premostenia', 'Rok_postavenia',
       'Zaťažovacia_trieda_STN', 'Počet_otvorov', 'Dĺžka_premostenia',
       'Dĺžka_nosnej_konštrukcie_m', 'Volná_šírka_mosta',
       'Šírka_medzi_obrubami_m', 'Plocha_mosnej_konštrukcie_m2',
       'Plocha_mosta_m2', 'Vlastník_úseku', 'Správca_úseku', 'Okres',
       'Smer_úseku', 'Typ_úseku', 'Počiatočný_uzol', 'Koncový_uzol', 'úsek_ID',
       'úsekové_staničenie_začiatku_DC_m',
       'Kilometrovníkové_staničenie_začiatku_DC_km',
       'Kumulatívne_staničenie_začiatku_DC_km', 'Poradie', 'Kraj', 'n_2012',
       'n_2013', 'n_2014', 'n_2015', 'n_2016', 'n_2017', 'n_2018', 'n_2019',
       'n_2020', 'n_2021', 'n_2022', 'n_2023'],
      dtype='object')

In [231]:
# Create a dictionary from df_bridges mapping 'ID mosta' to 'n_2024'
id_to_condition_mapping = df_bridges.set_index('ID mosta')['n_2024'].to_dict()

# Map this dictionary to df_bridges_all['ID_mosta'] to create a new 'n_2024' column
df_bridges_all['n_2024'] = df_bridges_all['ID_mosta'].map(
    id_to_condition_mapping)

df_bridges_all

,ID_mosta,Trieda_PK,Číslo_PK,Most_DC,Názov_mosta,ID_DC,správcovské_číslo,Zemepisná_šírka,Zemepisná_dĺžka,Výška,...,n_2015,n_2016,n_2017,n_2018,n_2019,n_2020,n_2021,n_2022,n_2023,n_2024
0,M5897,cesta I. triedy,2,Dilatačný celok,02_002 Most cez potok Brestovec v obci Kopčany,M5897.01,2,48.790152,17.123319,163.816250,...,3,3,5,5,5,5,5,5,5,5.0
1,M1979,cesta I. triedy,2,Dilatačný celok,02_003 Most cez Cuninský potok medzi obcami Ko...,M1979.01,3,48.757287,17.079098,162.974249,...,3,3,6,6,6,6,6,6,6,6.0
2,M6525,cesta I. triedy,2,Dilatačný celok,02_004 Most nad železnicou Praha - Bratislava ...,M6525.01,4,48.684515,17.031675,168.968750,...,4,4,4,4,4,4,4,4,4,4.0
3,M4584,cesta I. triedy,2,Dilatačný celok,O2_005 Most cez Zelnický potok pred obcou Kúty,M4584.01,5,48.663688,17.020574,155.871499,...,3,3,3,3,3,3,3,3,4,5.0
4,M3053,cesta I. triedy,2,Dilatačný celok,"02_006 Most nad diaľnicou D2, pri obci Kúty",M3053.01,6,48.639120,17.001660,161.480000,...,4,4,4,4,4,4,5,5,5,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8120,M9963,diaľnica,R2,Dilatačný celok,"Most nad PC v km 9,000",M9963.01,SO 212-0,48.474460,19.533000,271.742065,...,0,0,0,0,0,0,0,0,2,2.0
8121,M9965,diaľnica,R2,Dilatačný celok,"Most na R2 nad III/2632 km 10,500",M9965.01,SO 214,48.465050,19.547370,262.075714,...,0,0,0,0,0,0,0,0,2,2.0
8122,M9966,diaľnica,R2,Dilatačný celok,"Most na R2 v km 11,450",M9966.01,SO 215,48.462190,19.559300,255.026825,...,0,0,0,0,0,0,0,0,2,2.0
8123,M9967,diaľnica,R2,Dilatačný celok,"Most na R2 nad PC v km 14,500",M9967.01,SO 216,48.438690,19.579420,244.832169,...,0,0,0,0,0,0,0,0,2,2.0
8124,M9969,diaľnica,R2,Dilatačný celok,"Most na R2 nad Budinským potokom km 15,870",M9969.01,SO 218,48.427680,19.587270,227.332352,...,0,0,0,0,0,0,0,0,2,2.0

In [232]:
# First, filter df_bridges to only include rows with a known condition
known_condition_bridges = df_bridges.dropna(subset=['n_2024'])

# Convert the ID columns to sets for easier comparison
set_known_bridges = set(known_condition_bridges['ID mosta'])
set_bridges_all = set(df_bridges_all['ID_mosta'].dropna())

# Find bridges in known_condition_bridges that are not in df_bridges_all
missing_known_bridges = set_known_bridges - set_bridges_all

# Count these bridges
print(f'Number of bridges with known condition in df_bridges not found in df_bridges_all: {
      len(missing_known_bridges)}')

Number of bridges with known condition in df_bridges not found in df_bridges_all: 98

In [233]:
# Convert the set to a list for easier use in filtering
missing_known_bridges_list = list(missing_known_bridges)

# Create a mask that checks if 'ID mosta' or 'ID DC' contains any of the IDs in missing_known_bridges_list
mask = df_2024['ID mosta'].isin(
    missing_known_bridges_list) | df_2024['ID DC'].isin(missing_known_bridges_list)

# Filter df_2024 using the mask to create a new DataFrame
filtered_df_2024 = df_2024[mask]

# Display the filtered DataFrame to check the results
print(filtered_df_2024[['ID mosta', 'ID DC']].head())

     ID mosta  ID DC
210     M5938   None
211       NaN  M5938
1142    M9914   None
1143      NaN  M9914
1212    M9577   None

In [234]:
# Define the file path for saving the CSV file
output_csv_path = r"C:\Users\relia\Documents\GitHub\Bridges\Data\df_bridges_2024.csv"

# Save the DataFrame as a CSV file
df_bridges_all.to_csv(output_csv_path, index=False)

In [235]:
# Define the file path for saving the CSV file
output_csv_path = r"C:\Users\relia\Documents\GitHub\Bridges\Data\filtered_df_2024.csv"

# Save the DataFrame as a CSV file
filtered_df_2024.to_csv(output_csv_path, index=False)

In [236]:
# # Define the file path for saving the CSV file
# output_csv_path = r"C:\Users\relia\Documents\GitHub\Bridges\Data\df_2024.csv"

# # Save the DataFrame as a CSV file
# df_2024.to_csv(output_csv_path, index=False)